#include <stdio.h>
#include "ble_log.h"


char* gattc_events_to_name(esp_gattc_cb_event_t event)
{
    switch (event)
    {
        case ESP_GATTC_REG_EVT: return("ESP_GATTC_REG_EVT");
        case ESP_GATTC_UNREG_EVT: return("ESP_GATTC_UNREG_EVT");
        case ESP_GATTC_OPEN_EVT: return("ESP_GATTC_OPEN_EVT");
        case ESP_GATTC_READ_CHAR_EVT: return("ESP_GATTC_READ_CHAR_EVT");
        case ESP_GATTC_WRITE_CHAR_EVT: return("ESP_GATTC_WRITE_CHAR_EVT");
        case ESP_GATTC_CLOSE_EVT: return("ESP_GATTC_CLOSE_EVT");
        case ESP_GATTC_SEARCH_CMPL_EVT: return("ESP_GATTC_SEARCH_CMPL_EVT");
        case ESP_GATTC_SEARCH_RES_EVT: return("ESP_GATTC_SEARCH_RES_EVT");
        case ESP_GATTC_READ_DESCR_EVT: return("ESP_GATTC_READ_DESCR_EVT");
        case ESP_GATTC_WRITE_DESCR_EVT: return("ESP_GATTC_WRITE_DESCR_EVT");
        case ESP_GATTC_NOTIFY_EVT: return("ESP_GATTC_NOTIFY_EVT");
        case ESP_GATTC_PREP_WRITE_EVT: return("ESP_GATTC_PREP_WRITE_EVT");
        case ESP_GATTC_EXEC_EVT: return("ESP_GATTC_EXEC_EVT");
        case ESP_GATTC_ACL_EVT: return("ESP_GATTC_ACL_EVT");
        case ESP_GATTC_CANCEL_OPEN_EVT: return("ESP_GATTC_CANCEL_OPEN_EVT");
        case ESP_GATTC_SRVC_CHG_EVT: return("ESP_GATTC_SRVC_CHG_EVT");
        case ESP_GATTC_ENC_CMPL_CB_EVT: return("ESP_GATTC_ENC_CMPL_CB_EVT");
        case ESP_GATTC_CFG_MTU_EVT: return("ESP_GATTC_CFG_MTU_EVT");
        case ESP_GATTC_ADV_DATA_EVT: return("ESP_GATTC_ADV_DATA_EVT");
        case ESP_GATTC_MULT_ADV_ENB_EVT: return("ESP_GATTC_MULT_ADV_ENB_EVT");
        case ESP_GATTC_MULT_ADV_UPD_EVT: return("ESP_GATTC_MULT_ADV_UPD_EVT");
        case ESP_GATTC_MULT_ADV_DATA_EVT: return("ESP_GATTC_MULT_ADV_DATA_EVT");
        case ESP_GATTC_MULT_ADV_DIS_EVT: return("ESP_GATTC_MULT_ADV_DIS_EVT");
        case ESP_GATTC_CONGEST_EVT: return("ESP_GATTC_CONGEST_EVT");
        case ESP_GATTC_BTH_SCAN_ENB_EVT: return("ESP_GATTC_BTH_SCAN_ENB_EVT");
        case ESP_GATTC_BTH_SCAN_CFG_EVT: return("ESP_GATTC_BTH_SCAN_CFG_EVT");
        case ESP_GATTC_BTH_SCAN_RD_EVT: return("ESP_GATTC_BTH_SCAN_RD_EVT");
        case ESP_GATTC_BTH_SCAN_THR_EVT: return("ESP_GATTC_BTH_SCAN_THR_EVT");
        case ESP_GATTC_BTH_SCAN_PARAM_EVT: return("ESP_GATTC_BTH_SCAN_PARAM_EVT");
        case ESP_GATTC_BTH_SCAN_DIS_EVT: return("ESP_GATTC_BTH_SCAN_DIS_EVT");
        case ESP_GATTC_SCAN_FLT_CFG_EVT: return("ESP_GATTC_SCAN_FLT_CFG_EVT");
        case ESP_GATTC_SCAN_FLT_PARAM_EVT: return("ESP_GATTC_SCAN_FLT_PARAM_EVT");
        case ESP_GATTC_SCAN_FLT_STATUS_EVT: return("ESP_GATTC_SCAN_FLT_STATUS_EVT");
        case ESP_GATTC_ADV_VSC_EVT: return("ESP_GATTC_ADV_VSC_EVT");
        case ESP_GATTC_REG_FOR_NOTIFY_EVT: return("ESP_GATTC_REG_FOR_NOTIFY_EVT");
        case ESP_GATTC_UNREG_FOR_NOTIFY_EVT: return("ESP_GATTC_UNREG_FOR_NOTIFY_EVT");
        case ESP_GATTC_CONNECT_EVT: return("ESP_GATTC_CONNECT_EVT");
        case ESP_GATTC_DISCONNECT_EVT: return("ESP_GATTC_DISCONNECT_EVT");
        case ESP_GATTC_READ_MULTIPLE_EVT: return("ESP_GATTC_READ_MULTIPLE_EVT");
        case ESP_GATTC_QUEUE_FULL_EVT: return("ESP_GATTC_QUEUE_FULL_EVT");
        case ESP_GATTC_SET_ASSOC_EVT: return("ESP_GATTC_SET_ASSOC_EVT");
        case ESP_GATTC_GET_ADDR_LIST_EVT: return("ESP_GATTC_GET_ADDR_LIST_EVT");
        case ESP_GATTC_DIS_SRVC_CMPL_EVT: return("ESP_GATTC_DIS_SRVC_CMPL_EVT");
        default: return("event unknow");

    }
    
}

char* gap_events_to_name (esp_gap_ble_cb_event_t event)
{
    switch (event)
    {
        case ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT: return("ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_RSP_DATA_SET_COMPLETE_EVT: return("ESP_GAP_BLE_SCAN_RSP_DATA_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_PARAM_SET_COMPLETE_EVT: return("ESP_GAP_BLE_SCAN_PARAM_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_RESULT_EVT: return("ESP_GAP_BLE_SCAN_RESULT_EVT");
        case ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT: return("ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_RSP_DATA_RAW_SET_COMPLETE_EVT: return("ESP_GAP_BLE_SCAN_RSP_DATA_RAW_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_ADV_START_COMPLETE_EVT: return("ESP_GAP_BLE_ADV_START_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_START_COMPLETE_EVT: return("ESP_GAP_BLE_SCAN_START_COMPLETE_EVT");
        case ESP_GAP_BLE_AUTH_CMPL_EVT: return("ESP_GAP_BLE_AUTH_CMPL_EVT");
        case ESP_GAP_BLE_KEY_EVT: return("ESP_GAP_BLE_KEY_EVT");
        case ESP_GAP_BLE_SEC_REQ_EVT: return("ESP_GAP_BLE_SEC_REQ_EVT");
        case ESP_GAP_BLE_PASSKEY_NOTIF_EVT: return("ESP_GAP_BLE_PASSKEY_NOTIF_EVT");
        case ESP_GAP_BLE_PASSKEY_REQ_EVT: return("ESP_GAP_BLE_PASSKEY_REQ_EVT");
        case ESP_GAP_BLE_OOB_REQ_EVT: return("ESP_GAP_BLE_OOB_REQ_EVT");
        case ESP_GAP_BLE_LOCAL_IR_EVT: return("ESP_GAP_BLE_LOCAL_IR_EVT");
        case ESP_GAP_BLE_LOCAL_ER_EVT: return("ESP_GAP_BLE_LOCAL_ER_EVT");
        case ESP_GAP_BLE_NC_REQ_EVT: return("ESP_GAP_BLE_NC_REQ_EVT");
        case ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT: return("ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT");
        case ESP_GAP_BLE_SCAN_STOP_COMPLETE_EVT: return("ESP_GAP_BLE_SCAN_STOP_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_STATIC_RAND_ADDR_EVT: return("ESP_GAP_BLE_SET_STATIC_RAND_ADDR_EVT");
        case ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT: return("ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT");
        case ESP_GAP_BLE_SET_PKT_LENGTH_COMPLETE_EVT: return("ESP_GAP_BLE_SET_PKT_LENGTH_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_LOCAL_PRIVACY_COMPLETE_EVT: return("ESP_GAP_BLE_SET_LOCAL_PRIVACY_COMPLETE_EVT");
        case ESP_GAP_BLE_REMOVE_BOND_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_REMOVE_BOND_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_CLEAR_BOND_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_CLEAR_BOND_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_GET_BOND_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_GET_BOND_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_READ_RSSI_COMPLETE_EVT: return("ESP_GAP_BLE_READ_RSSI_COMPLETE_EVT");
        case ESP_GAP_BLE_UPDATE_WHITELIST_COMPLETE_EVT: return("ESP_GAP_BLE_UPDATE_WHITELIST_COMPLETE_EVT");
        case ESP_GAP_BLE_UPDATE_DUPLICATE_EXCEPTIONAL_LIST_COMPLETE_EVT: return("ESP_GAP_BLE_UPDATE_DUPLICATE_EXCEPTIONAL_LIST_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_CHANNELS_EVT: return("ESP_GAP_BLE_SET_CHANNELS_EVT");
        case ESP_GAP_BLE_READ_PHY_COMPLETE_EVT: return("ESP_GAP_BLE_READ_PHY_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_PREFERED_DEFAULT_PHY_COMPLETE_EVT: return("ESP_GAP_BLE_SET_PREFERED_DEFAULT_PHY_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_PREFERED_PHY_COMPLETE_EVT: return("ESP_GAP_BLE_SET_PREFERED_PHY_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_SET_RAND_ADDR_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_SET_RAND_ADDR_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_SET_PARAMS_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_SET_PARAMS_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_DATA_SET_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_DATA_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_SCAN_RSP_DATA_SET_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_SCAN_RSP_DATA_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_START_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_START_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_STOP_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_STOP_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_SET_REMOVE_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_SET_REMOVE_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_SET_CLEAR_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_ADV_SET_CLEAR_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_SET_PARAMS_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_SET_PARAMS_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_DATA_SET_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_DATA_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_START_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_START_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_STOP_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_STOP_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_CREATE_SYNC_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_CREATE_SYNC_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_SYNC_CANCEL_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_SYNC_CANCEL_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_SYNC_TERMINATE_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_SYNC_TERMINATE_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_ADD_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_ADD_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_REMOVE_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_REMOVE_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_CLEAR_DEV_COMPLETE_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_CLEAR_DEV_COMPLETE_EVT");
        case ESP_GAP_BLE_SET_EXT_SCAN_PARAMS_COMPLETE_EVT: return("ESP_GAP_BLE_SET_EXT_SCAN_PARAMS_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_SCAN_START_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_SCAN_START_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_SCAN_STOP_COMPLETE_EVT: return("ESP_GAP_BLE_EXT_SCAN_STOP_COMPLETE_EVT");
        case ESP_GAP_BLE_PREFER_EXT_CONN_PARAMS_SET_COMPLETE_EVT: return("ESP_GAP_BLE_PREFER_EXT_CONN_PARAMS_SET_COMPLETE_EVT");
        case ESP_GAP_BLE_PHY_UPDATE_COMPLETE_EVT: return("ESP_GAP_BLE_PHY_UPDATE_COMPLETE_EVT");
        case ESP_GAP_BLE_EXT_ADV_REPORT_EVT: return("ESP_GAP_BLE_EXT_ADV_REPORT_EVT");
        case ESP_GAP_BLE_SCAN_TIMEOUT_EVT: return("ESP_GAP_BLE_SCAN_TIMEOUT_EVT");
        case ESP_GAP_BLE_ADV_TERMINATED_EVT: return("ESP_GAP_BLE_ADV_TERMINATED_EVT");
        case ESP_GAP_BLE_SCAN_REQ_RECEIVED_EVT: return("ESP_GAP_BLE_SCAN_REQ_RECEIVED_EVT");
        case ESP_GAP_BLE_CHANNEL_SELETE_ALGORITHM_EVT: return("ESP_GAP_BLE_CHANNEL_SELETE_ALGORITHM_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_REPORT_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_REPORT_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_SYNC_LOST_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_SYNC_LOST_EVT");
        case ESP_GAP_BLE_PERIODIC_ADV_SYNC_ESTAB_EVT: return("ESP_GAP_BLE_PERIODIC_ADV_SYNC_ESTAB_EVT");
        case ESP_GAP_BLE_EVT_MAX: return("ESP_GAP_BLE_EVT_MAX");
        default: return("unknow event");
    }
}

char* gatt_conn_to_name(esp_gatt_conn_reason_t reason) 
{
    switch(reason)
    {
        case ESP_GATT_CONN_UNKNOWN: return("ESP_GATT_CONN_UNKNOWN");
        case ESP_GATT_CONN_L2C_FAILURE: return("ESP_GATT_CONN_L2C_FAILURE");
        case ESP_GATT_CONN_TIMEOUT: return("ESP_GATT_CONN_TIMEOUT");
        case ESP_GATT_CONN_TERMINATE_PEER_USER: return("ESP_GATT_CONN_TERMINATE_PEER_USER");
        case ESP_GATT_CONN_TERMINATE_LOCAL_HOST: return("ESP_GATT_CONN_TERMINATE_LOCAL_HOST");
        case ESP_GATT_CONN_FAIL_ESTABLISH: return("ESP_GATT_CONN_FAIL_ESTABLISH");
        case ESP_GATT_CONN_LMP_TIMEOUT: return("ESP_GATT_CONN_LMP_TIMEOUT");
        case ESP_GATT_CONN_CONN_CANCEL: return("ESP_GATT_CONN_CONN_CANCEL");
        case ESP_GATT_CONN_NONE: return("ESP_GATT_CONN_NONE");
        default: return ("unknow reason");
    }
}